### ISSUE TITLE
Configurability of HostAndPort

### ISSUE THREAD

**Issue by type0lang** [smoketurner/dropwizard-consul#27]
Hi JPlock,

the `consul.endpoint` param within the yaml configuration file (see further) is not taken into consideration while building the `ConsulClient`. As specified into the source code I must override `getConsulAgentHost()` and `getConsulAgentPort()`, forcing to fetch the host and the port somewhere else outside of the configuration. Is it correct?

```java
//        Backends - Consul
        bootstrap.addBundle(new ConsulBundle<ListenerApplicationConfiguration>(this.getName()) {
            @Override
            public ConsulFactory getConsulFactory(ListenerApplicationConfiguration conf) {
                return conf.getConsul();
            }

            @Override
            public String getConsulAgentHost() {
                return "--->WhereDoIGetTheHost?<---" }

            @Override
            public int getConsulAgentPort() {
                return "--->WhereDoIGetThePort?<---"; }
        });
```

```yaml
consul:
  # Optional properties
  # endpoint for consul (defaults to localhost:8500)
  endpoint: consul.cluster.mydomain.com:8500
  # service port
  servicePort: 8080

  # service port
  adminPort: 8081

  # check interval frequency
  checkInterval: 10 seconds

```

**Comment by jplock** [comment]
What are you are doing is the only way to override those variables if you are trying to change the cluster off of localhost for the KV lookup stuff.  I haven't figured out a better way to allow users to configure that.

**Comment by jplock** [comment]
If you don't need to do KV lookups in the configuration file, then you should just be able to set the endpoint.

**Comment by type0lang** [comment]
I'm basically using consul to register my dropwizard service and his healthchecks. The configurability is done with the configuration.yaml file. It seems that 
```yaml
consul:
  # Optional properties
  # endpoint for consul (defaults to localhost:8500)
  endpoint: consul.cluster.mydomain.com:8500
```

does not fetch the endpoint value but he still uses "localhost" as his default parameter.
you could avoid 
```java
new ConsulSubstitutor(Consul.builder().withHostAndPort(HostAndPort.fromParts(this.getConsulAgentHost(), this.getConsulAgentPort())).build(), this.strict, this.substitutionInVariables)
```
substituting `this.getConsulAgentHost(), this.getConsulAgentPort()` and taking it from the configuration yaml.
